# Generated by Django 5.1.6 on 2025-02-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_owner'),
        ('users', '0002_rename_profie_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='reviews.anime'),
        ),
    ]
